version: '3.10'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    command: -token ${DISCORD_TOKEN} -host ${SD_URL} -guild ${DISCORD_GUILD}

