# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  xgo:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.18
          dest: build
          prefix: stable_diffusion_bot
          targets: linux/386,linux/amd64,linux/arm64,windows/386,windows/amd64,darwin/amd64,darwin/arm64
          v: false
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
